### ISSUE TITLE
Help wanted - fatal error: unreachable method called. linker bug?

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#131]
## Question

`./dtm check` will get the right result.
`./smoke` will get the panic

## Screenshots

![image](https://user-images.githubusercontent.com/18692628/149664163-68a96fe1-7775-4dc8-9181-04d8d9d2ae25.png)

![image](https://user-images.githubusercontent.com/18692628/149664328-b18578f2-ee2d-4ef7-85bb-6e0c15a1410d.png)

**Comment by IronCore864** [comment]
Background: we are doing end-to-end test and want the `smoke` binary to call the `pluginengine` but inconsistent behavior occurred (compared to triggering the `plugineingine` by `cobra`.

After some thoughts, maybe it's better if we put what the `smoke` is supposed to do as a stand-alone `dtm` sub-command (i.e., `dtm verify`), and the end-to-end test can be a shell script which calls `dtm apply` then `dtm verify`.

The reason is twofold:
- the current `smoke` calls the `plugineingine` directly, which isn't exactly "end-to-end";
- `dtm verify` can be a useful feature for our users as well.
