### ISSUE TITLE
Bug: `dtm verify` shouldn't return any error before `dtm apply`

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#255]
## Describe the Bug

If the users forget to execute `dtm apply` after `dtm init`, but directly execute `dtm verify`, error log should not be output at this time.

See the https://github.com/merico-dev/stream/issues/252#issue-1156718149 for more info.

## How to Reproduce

See the https://github.com/merico-dev/stream/issues/252#issue-1156718149 for more info.

**Comment by IronCore864** [comment]
Thanks @imxw for submitting the [issue](https://github.com/merico-dev/stream/issues/252)!

This is a very good issue that emphasizes many points:

1. `dtm verify` should not "fail" or "error" in any circumstances. The purpose of the "verify", as the word means, is to make sure if something is as expected.
2. The "error" in the log is a bit too much. If an "error" message is displayed, the user might think something went wrong or something they did is wrong, which isn't the case in the original post's issue.

And this got us thinking: what exactly should `verify` do, and how will the users know the expected behavior of `verify`?

This leads to another point: we should have dedicated documentation explaining how everything works.

Thanks again for this great issue; a PR fixing it is on the way.
