### ISSUE TITLE
Proposal: Automatically build the makefile from the cmd directory

### ISSUE THREAD

**Issue by summingyu** [merico-dev/stream#348]
## Description

After we build the plugin automatically, can we find the plugin directory and automatically build the .so file with the corresponding plugin name by combining the "for" function of the makefile, instead of modifying the makefile file manually?

## Describe the Alternatives You Have Considered

This is the function I used to test the build, which passed the local test and was successful when I built a task manually
![image](https://user-images.githubusercontent.com/17695185/159875243-8784ffa9-acf8-4ba6-bd52-26462536846d.png)

`build fortest`
![image](https://user-images.githubusercontent.com/17695185/159875737-23c368b5-60ac-40fa-9f50-f258a1784d22.png)

`dtm apply -f config.yaml`
![image](https://user-images.githubusercontent.com/17695185/159875545-0a9feeba-c0bc-46b4-a04d-898ae8c04a6b.png)

The following should be noted:
1. need to standardize the naming of some .so files, such as trello-github-integ, github-repo-scaffolding-golang, etc.
2. need to unify some `docs/plugins/{plugins_name}.md` inside the kind type
3. need to standardize the naming in `build/package/build_linux_adm64.sh`.

Or more

**Comment by daniel-hutao** [comment]
Great thinking!

`trello-github-integ` is a canonical name that represents a plugin for the integration of `trello` and `github`, but the correspondence with the package name did become inconsistent. This is a problem we need to think about.

**Comment by daniel-hutao** [comment]
Or we can refactor the cmd package with:

```
- cmd 
  - devstream
  - plugin
     - argocd
     - githubactions-golang
     - githubactions-python
     - ...
```

@IronCore864 @lfbdev agree?

**Comment by IronCore864** [comment]
Very good proposal!

After internal discussion within the PMC, we decided the followings need to be done in order to consider this issue resolved:

1. Directory naming: use hyphen (-) instead of underscore （_). This convention must be strictly followed for _ALL_ directories in this repo.
2. File naming: use underscore (_). We are already doing this. We need to make sure no file is named with hypyen (-)
3. Package naming: as per Go naming convention, package naming doesn't allow hyphen or underscore because it should be an identifier. For example, if the directory's name is "github-repo-scaffolding-golang", the package name could be "githubreposcaffoldinggolang". If this is too long, abbreviation is allowed, for example, "ghreposcaffgo", but we should use the same (either full or abbr.) for all similar types of plugins.
4. A documentation must be created (either a new doc, or in an existing doc, for example, CONTRIBUTING) to clarify these points, so that every community member can follow exactly the same convention.

**Comment by summingyu** [comment]
Standardization is necessary, but
I started with just this idea: I wanted a fixed function to get all the plugin names and plugin directories used for building, so that I don't have to modify the makefile file when adding plugins.😂

**Comment by daniel-hutao** [comment]
Scope：

@daniel-hutao 

Refactoring the `cmd` package to keep the dir-name same as the plugin's name.

@summingyu 

Refactoring

- Makefile
- build/package/build_linux_adm64.sh 

@IronCore864 

All the docs related.
